### ISSUE TITLE
UI Errors

### ISSUE THREAD

**Issue by epicacrylic** [jakadak/ahud-cc#1]
Two things I noticed so far:

- Both "Open {x} loadout..." and "Ok, resume game" for any item (trade, found, etc.) doesn't work
- It's inconsistent, but the killstreak icon will be in the middle of the HUD under the Red team, basically a whole match, then disappear again

**Comment by jakadak** [comment]
So I fixed the killstreak icon:  https://github.com/jakadak/ahud-cc/commit/6efce1782734210071a29a82a53e6dc10f15aa58

From my experience, the item buttons are a regular HUD issue (https://steamcommunity.com/app/440/discussions/0/3145094199288751666/?l=bulgarian). However, I noticed that they may occur more often than usual.

**Comment by jakadak** [comment]
And I also deleted the original New Item panel, so it should be more ok
