### ISSUE TITLE
"Default" ubercharge hud location does not have drop-shadows on the text

### ISSUE THREAD

**Issue by BetaSigmaOmega** [jakadak/ahud-cc#10]
ahud-cc version:
![image](https://github.com/user-attachments/assets/aa97abc2-9c66-478e-be17-4de2ae924c2a)

original ahud version:
![image](https://github.com/user-attachments/assets/6529b18d-8d91-49f2-aa58-cccfe8c72043)

**Comment by jakadak** [comment]
Yess, unfortunately I had to do this, so my vaccinator HUD could be semi-transparent
