### ISSUE TITLE
Scoreboard doesn't show players, score and ping after the scream fortress XVI update

### ISSUE THREAD

**Issue by Darkrobot1000** [jakadak/ahud-cc#7]
![image](https://github.com/user-attachments/assets/2e865138-b9e7-412e-aacf-8bb770ccae03)
![image](https://github.com/user-attachments/assets/542c045e-cb78-4b8d-bd85-bc2a59a8c9b2)
![image](https://github.com/user-attachments/assets/da51e005-c9e2-4da4-962e-326718282925)
![image](https://github.com/user-attachments/assets/5f567019-828a-4528-b5fa-29b75e9c0218)

I do not use streamer mode and I don't have any other mods installed that could screw around with the scoreboard UI and before the scream fortress update I had no issues with the scoreboard.

**Comment by simonyassine** [comment]
same here

**Comment by epicacrylic** [comment]
Having [this](https://youtu.be/LHovj68rLiw) happen

Also the text for right clicking options on main menu as well as text for joining a team were rather huge as well,
![image](https://github.com/user-attachments/assets/4dbe0aff-205a-4d1f-ae76-f50c7a0f5488)

**Comment by CrazyShootin** [comment]
This is happening cause of the latest update changing UI scaling, so there can happen some bugs like not seeing the scoreboard/text is massive. Hopefully a patch regarding this is done soon
![image_2024-10-13_180532174](https://github.com/user-attachments/assets/d1c6dd9e-2663-4a8a-b136-bdf9fc5b2145)

**Comment by epicacrylic** [comment]
Figured as much, however I have seen one custom HUD not have this problem, so I figured I'd report either way. The large text on the main menu happens even with default scoreboard (removed the scoreboard related files from ahud to test out) so that's a base game issue as well
